// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.System.Crm.Infrastructure.Persistence.Contexts;

#nullable disable

namespace Modules.System.Crm.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modules.System.Crm.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateOnly?>("Birthday").HasColumnType("date");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("CreatedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Gender").HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<bool>("IsVip").HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LastModifiedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid?>("LastModifiedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("LastModifiedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Mobile").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<string>("NormalizedMobile").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<string>("Notes").HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                    b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("UserId").HasColumnType("uniqueidentifier");

                    b.HasKey("Id");
                    b.HasAlternateKey("Id", "TenantId");
                    b.HasIndex("CreatedAt").IsDescending();
                    b.HasIndex("TenantId", "IsActive");
                    b.HasIndex("TenantId", "NormalizedMobile")
                        .IsUnique()
                        .HasDatabaseName("UX_Customers_TenantId_NormalizedMobile");
                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL")
                        .HasDatabaseName("UX_Customers_TenantId_UserId");
                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Modules.System.Crm.Domain.Entities.CustomerNote", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<string>("Content").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("CreatedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<Guid>("CustomerId").HasColumnType("uniqueidentifier");
                    b.Property<DateTimeOffset?>("LastModifiedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid?>("LastModifiedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("LastModifiedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                    b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");

                    b.HasKey("Id");
                    b.HasIndex("CreatedAt").IsDescending();
                    b.HasIndex("CustomerId", "TenantId");
                    b.HasIndex("TenantId", "CustomerId", "CreatedAt");
                    b.ToTable("CustomerNotes");
                });

            modelBuilder.Entity("Modules.System.Crm.Domain.Entities.CustomerNote", b =>
                {
                    b.HasOne("Modules.System.Crm.Domain.Entities.Customer", "Customer")
                        .WithMany("NoteEntries")
                        .HasForeignKey("CustomerId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Modules.System.Crm.Domain.Entities.Customer", b =>
                {
                    b.Navigation("NoteEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
