<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Modules.Identity\Modules.Identity.csproj" />
    <ProjectReference Include="..\Modules.Services\Modules.Services.csproj" />
    <ProjectReference Include="..\Modules.Workforce\Modules.Workforce.csproj" />
    <ProjectReference Include="..\Modules.Crm\Modules.Crm.csproj" />
    <ProjectReference Include="..\Web.Sharedkernel\Web.Sharedkernel.csproj" />
  </ItemGroup>

</Project>
