using Scalar.ClientGeneration.Generation.TypeScript;

namespace Scalar.ClientGeneration.Generation.Angular;

internal sealed class AngularIndexGenerator
{
    public GeneratedSourceFile Generate(
        string groupName)
    {
        var fileName =
            TypeScriptNameHelper.ToKebabCase(
                groupName);

        var content = $$"""
            // Generated by Scalar.ClientGeneration
            // Do not edit manually.

            export * from './{{fileName}}.models';
            export * from './{{fileName}}.client';
            """;

        return new GeneratedSourceFile(
            FileName: "index.ts",
            Content: content);
    }
}