using System.Text;
using Scalar.ClientGeneration.Generation.Models;

namespace Scalar.ClientGeneration.Generation.TypeScript;

internal sealed class TypeScriptModelsGenerator(
    TypeScriptTypeFormatter typeFormatter)
{
    public GeneratedSourceFile Generate(
        ClientApiDefinition definition)
    {
        ArgumentNullException.ThrowIfNull(
            definition);

        var builder =
            new StringBuilder();

        builder.AppendLine(
            "// Generated by Scalar.ClientGeneration");

        builder.AppendLine(
            $"// Group: {definition.Group.Name}");

        builder.AppendLine(
            "// Do not edit manually.");

        builder.AppendLine();

        //
        // Enums
        //
        foreach (var clientEnum
                 in definition.Enums)
        {
            WriteEnum(
                builder,
                clientEnum);

            builder.AppendLine();
        }

        //
        // Models
        //
        foreach (var model
                 in definition.Models)
        {
            WriteModel(
                builder,
                model);

            builder.AppendLine();
        }

        var groupName =
            TypeScriptNameHelper
                .ToKebabCase(
                    definition.Group.Name);

        return new GeneratedSourceFile(
            $"{groupName}.models.ts",
            builder.ToString());
    }

    private void WriteEnum(
     StringBuilder builder,
     ClientEnum clientEnum)
    {
        builder.AppendLine(
            $"export const {clientEnum.Name} = {{");

        foreach (var value
                 in clientEnum.Values)
        {
            var literal =
                FormatEnumValue(
                    value);

            builder.AppendLine(
                $"    {value.Name}: {literal},");
        }

        builder.AppendLine(
            "} as const;");

        builder.AppendLine();

        builder.AppendLine(
            $"export type {clientEnum.Name} =");

        builder.AppendLine(
            $"    typeof {clientEnum.Name}[");

        builder.AppendLine(
            $"        keyof typeof {clientEnum.Name}");

        builder.AppendLine(
            "    ];");
    }

    private static string FormatEnumValue(
    ClientEnumValue value)
    {
        if (!value.IsString)
        {
            return value.Value;
        }

        var escaped =
            value.Value
                .Replace("\\", "\\\\")
                .Replace("'", "\\'");

        return $"'{escaped}'";
    }

    private void WriteModel(
        StringBuilder builder,
        ClientModel model)
    {
        builder.AppendLine(
            $"export interface {model.Name} {{");

        foreach (var property
                 in model.Properties)
        {
            var propertyName =
                TypeScriptNameHelper.Property(
                    property.Name);

            var optional =
                property.Required
                    ? string.Empty
                    : "?";

            var type =
                typeFormatter.Format(
                    property.Type);

            builder.AppendLine(
                $"    {propertyName}{optional}: {type};");
        }

        builder.AppendLine("}");
    }
}