// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.System.Services.Infrastructure.Persistence.Contexts;

#nullable disable

namespace Modules.System.Services.Migrations
{
    [DbContext(typeof(ServicesDbContext))]
    partial class ServicesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modules.System.Services.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("CreatedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<string>("Description").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LastModifiedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid?>("LastModifiedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("LastModifiedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                    b.Property<int>("SortOrder").HasColumnType("int");
                    b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");

                    b.HasKey("Id");
                    b.HasAlternateKey("Id", "TenantId");
                    b.HasIndex("CreatedAt").IsDescending();
                    b.HasIndex("TenantId", "IsActive", "SortOrder");
                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("Modules.System.Services.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<Guid>("CategoryId").HasColumnType("uniqueidentifier");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("CreatedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<string>("Description").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                    b.Property<int>("DurationMinutes").HasColumnType("int");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LastModifiedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid?>("LastModifiedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("LastModifiedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                    b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");

                    b.HasKey("Id");
                    b.HasIndex("CategoryId", "TenantId");
                    b.HasIndex("CreatedAt").IsDescending();
                    b.HasIndex("TenantId", "CategoryId", "IsActive");
                    b.ToTable("Services");
                });

            modelBuilder.Entity("Modules.System.Services.Domain.Entities.Service", b =>
                {
                    b.HasOne("Modules.System.Services.Domain.Entities.ServiceCategory", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Modules.System.Services.Domain.Entities.ServiceCategory", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
