// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.System.Workforce.Infrastructure.Persistence.Contexts;

#nullable disable

namespace Modules.System.Workforce.Migrations
{
    [DbContext(typeof(WorkforceDbContext))]
    partial class WorkforceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modules.System.Workforce.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("CreatedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                    b.Property<string>("FirstName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LastModifiedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid?>("LastModifiedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("LastModifiedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<string>("LastName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<string>("Phone").IsRequired().HasMaxLength(32).HasColumnType("nvarchar(32)");
                    b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                    b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");
                    b.Property<Guid?>("UserId").HasColumnType("uniqueidentifier");

                    b.HasKey("Id");
                    b.HasAlternateKey("Id", "TenantId");
                    b.HasIndex("CreatedAt").IsDescending();
                    b.HasIndex("TenantId", "IsActive");
                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL")
                        .HasDatabaseName("UX_Staff_TenantId_UserId");
                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Modules.System.Workforce.Domain.Entities.StaffScheduleBreak", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("CreatedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<TimeOnly>("EndTime").HasColumnType("time");
                    b.Property<DateTimeOffset?>("LastModifiedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid?>("LastModifiedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("LastModifiedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                    b.Property<Guid>("ScheduleDayId").HasColumnType("uniqueidentifier");
                    b.Property<TimeOnly>("StartTime").HasColumnType("time");
                    b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");

                    b.HasKey("Id");
                    b.HasIndex("CreatedAt").IsDescending();
                    b.HasIndex("ScheduleDayId", "TenantId");
                    b.HasIndex("TenantId", "ScheduleDayId", "StartTime", "EndTime").IsUnique();
                    b.ToTable("StaffScheduleBreaks", t =>
                        {
                            t.HasCheckConstraint("CK_StaffScheduleBreaks_TimeRange", "[StartTime] < [EndTime]");
                        });
                });

            modelBuilder.Entity("Modules.System.Workforce.Domain.Entities.StaffWeeklyScheduleDay", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("CreatedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<int>("DayOfWeek").HasColumnType("int");
                    b.Property<TimeOnly?>("EndTime").HasColumnType("time");
                    b.Property<bool>("IsDayOff").HasColumnType("bit");
                    b.Property<DateTimeOffset?>("LastModifiedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid?>("LastModifiedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("LastModifiedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                    b.Property<Guid>("StaffId").HasColumnType("uniqueidentifier");
                    b.Property<TimeOnly?>("StartTime").HasColumnType("time");
                    b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");

                    b.HasKey("Id");
                    b.HasAlternateKey("Id", "TenantId");
                    b.HasIndex("CreatedAt").IsDescending();
                    b.HasIndex("StaffId", "TenantId");
                    b.HasIndex("TenantId", "StaffId", "DayOfWeek").IsUnique();
                    b.ToTable("StaffWeeklyScheduleDays", t =>
                        {
                            t.HasCheckConstraint(
                                "CK_StaffWeeklyScheduleDays_DayOfWeek",
                                "[DayOfWeek] >= 0 AND [DayOfWeek] <= 6");

                            t.HasCheckConstraint(
                                "CK_StaffWeeklyScheduleDays_WorkingHours",
                                "([IsDayOff] = 1 AND [StartTime] IS NULL AND [EndTime] IS NULL) OR ([IsDayOff] = 0 AND [StartTime] IS NOT NULL AND [EndTime] IS NOT NULL AND [StartTime] < [EndTime])");
                        });
                });

            modelBuilder.Entity("Modules.System.Workforce.Domain.Entities.StaffBranch", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<Guid>("BranchId").HasColumnType("uniqueidentifier");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("CreatedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<DateTimeOffset?>("LastModifiedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid?>("LastModifiedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("LastModifiedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                    b.Property<Guid>("StaffId").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");

                    b.HasKey("Id");
                    b.HasIndex("CreatedAt").IsDescending();
                    b.HasIndex("StaffId", "TenantId");
                    b.HasIndex("TenantId", "BranchId");
                    b.HasIndex("TenantId", "StaffId", "BranchId").IsUnique();
                    b.ToTable("StaffBranches");
                });

            modelBuilder.Entity("Modules.System.Workforce.Domain.Entities.StaffService", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uniqueidentifier");
                    b.Property<DateTimeOffset>("CreatedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid>("CreatedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("CreatedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<DateTimeOffset?>("LastModifiedAt").HasColumnType("datetimeoffset");
                    b.Property<Guid?>("LastModifiedBy").HasColumnType("uniqueidentifier");
                    b.Property<string>("LastModifiedByIp").HasMaxLength(45).HasColumnType("nvarchar(45)");
                    b.Property<byte[]>("RowVersion").IsConcurrencyToken().IsRequired().ValueGeneratedOnAddOrUpdate().HasColumnType("rowversion");
                    b.Property<Guid>("ServiceId").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("StaffId").HasColumnType("uniqueidentifier");
                    b.Property<Guid>("TenantId").HasColumnType("uniqueidentifier");

                    b.HasKey("Id");
                    b.HasIndex("CreatedAt").IsDescending();
                    b.HasIndex("StaffId", "TenantId");
                    b.HasIndex("TenantId", "ServiceId");
                    b.HasIndex("TenantId", "StaffId", "ServiceId").IsUnique();
                    b.ToTable("StaffServices");
                });

            modelBuilder.Entity("Modules.System.Workforce.Domain.Entities.StaffBranch", b =>
                {
                    b.HasOne("Modules.System.Workforce.Domain.Entities.Staff", "Staff")
                        .WithMany("Branches")
                        .HasForeignKey("StaffId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Modules.System.Workforce.Domain.Entities.StaffService", b =>
                {
                    b.HasOne("Modules.System.Workforce.Domain.Entities.Staff", "Staff")
                        .WithMany("Services")
                        .HasForeignKey("StaffId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Modules.System.Workforce.Domain.Entities.StaffScheduleBreak", b =>
                {
                    b.HasOne("Modules.System.Workforce.Domain.Entities.StaffWeeklyScheduleDay", "ScheduleDay")
                        .WithMany("Breaks")
                        .HasForeignKey("ScheduleDayId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("ScheduleDay");
                });

            modelBuilder.Entity("Modules.System.Workforce.Domain.Entities.StaffWeeklyScheduleDay", b =>
                {
                    b.HasOne("Modules.System.Workforce.Domain.Entities.Staff", "Staff")
                        .WithMany("WeeklySchedule")
                        .HasForeignKey("StaffId", "TenantId")
                        .HasPrincipalKey("Id", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Modules.System.Workforce.Domain.Entities.Staff", b =>
                {
                    b.Navigation("Branches");
                    b.Navigation("Services");
                    b.Navigation("WeeklySchedule");
                });

            modelBuilder.Entity("Modules.System.Workforce.Domain.Entities.StaffWeeklyScheduleDay", b =>
                {
                    b.Navigation("Breaks");
                });
#pragma warning restore 612, 618
        }
    }
}
