<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<UserSecretsId>e241cc00-e041-4c00-8414-b7395f0b3e7a</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Application\Application.csproj" />
	  <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
	  <ProjectReference Include="..\Scalar.ClientGeneration\Scalar.ClientGeneration.csproj" />
	</ItemGroup>

</Project>
